import Head from "next/head";

// Import the shared function into the Next.js application
import { getSiteInfo } from "../../../../packages/site-info/index";

export default function Home() {
  const siteInfo = getSiteInfo(); //Define a variable to get the values
  return (
    <div>
      <Head>
        <title>{siteInfo.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Output the site title and subtitle to the screen*/}
      <main>
        <h1>Welcome to {siteInfo.title}</h1>
        <p>{siteInfo.subtitle}</p>
      </main>
    </div>
  );
}
